### ISSUE TITLE
Common names (instead of CURIEs) in heatmaps

### ISSUE THREAD

**Issue by ayushi-agrawal-gladstone** [wikipathways/BioThings_Explorer_PFOCR_prioritization#3]
The heatmaps with result CURIEs by pathway figures have NCBI Gene ids or MESH ids. These are less easier to remember for the user. Having the gene symbols, chemical names and disease names instead of CURIEs will be more useful. 

Suggested by @khanspers.

**Comment by AlexanderPico** [comment]
Done
